# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_mail',
            field=models.CharField(default='kim@gmail.com', max_length=100),
        ),
    ]
