# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-17 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_business_business_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighborhood',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='description',
            new_name='your_story',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='name',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='hood_image',
            new_name='diary_image',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='members',
            new_name='entries',
        ),
    ]
